export const usersData = [
  {
    id: 1,
    name: "Rahul Awasthi",
    email: "rahul.awasthi@reconcilx.com",
    role: "ADMIN",
    status: "ACTIVE",
    lastLogin: "06 Aug 2025, 10:24 AM",
    createdOn: "28 Jun 2025, 09:15 AM",
    createdBy: "Shweta",
    avatar: "RA",
  },
  {
    id: 2,
    name: "Neha Priyadarshini",
    email: "neha.priya@reconcilx.com",
    role: "ADMIN",
    status: "ACTIVE",
    lastLogin: "06 Aug 2025, 09:02 AM",
    createdOn: "04 Jul 2025, 02:30 PM",
    createdBy: "Rahul Awasthi",
    avatar: "NP",
  },
  {
    id: 3,
    name: "Manish Kumar",
    email: "manish.kumar@reconcilx.com",
    role: "MAKER",
    status: "ACTIVE",
    lastLogin: "05 Aug 2025, 04:45 PM",
    createdOn: "12 Jul 2025, 11:20 AM",
    createdBy: "Neha Priyadarshini",
    avatar: "MK",
  },
  {
    id: 4,
    name: "Pooja Sharma",
    email: "pooja.sharma@reconcilx.com",
    role: "MAKER",
    status: "ACTIVE",
    lastLogin: "05 Aug 2025, 01:10 PM",
    createdOn: "14 Jul 2025, 03:40 PM",
    createdBy: "Rahul Awasthi",
    avatar: "PS",
  },
  {
    id: 5,
    name: "Arjun Singh",
    email: "arjun.singh@reconcilx.com",
    role: "CHECKER",
    status: "ACTIVE",
    lastLogin: "04 Aug 2025, 05:35 PM",
    createdOn: "18 Jul 2025, 10:05 AM",
    createdBy: "Neha Priyadarshini",
    avatar: "AS",
  },
  {
    id: 6,
    name: "Dinesh Babu",
    email: "dinesh.babu@reconcilx.com",
    role: "CHECKER",
    status: "INACTIVE",
    lastLogin: "-",
    createdOn: "22 Jul 2025, 09:50 AM",
    createdBy: "Rahul Awasthi",
    avatar: "DB",
  },
  {
    id: 7,
    name: "Swati Kulkarni",
    email: "swati.kulkarni@reconcilx.com",
    role: "MAKER",
    status: "INACTIVE",
    lastLogin: "-",
    createdOn: "25 Jul 2025, 04:15 PM",
    createdBy: "Neha Priyadarshini",
    avatar: "SK",
  },
];
